spring:
  application:
    name: Desafio-picpay
  datasource:
    url: jdbc:postgresql://db:5432/picpay_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
